version: "3"

services:
  api:
    build: ./server
    ports:
      - "4444:4444"
    depends_on:
      - "desafio_dev_db"
    volumes:
        - ./src:/src
  desafio_dev_db:
    image: postgres
    container_name: desafio_dev_db
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWD}
    volumes:
      - pgdata:/data/postgres
    env_file:
      - ./server/.env
  web:
    build: .
    container_name: cnab_frontend
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true
volumes:
  pgdata:
    driver: local
  data:
    driver: local
